name: GitHub Pac-Man Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate Pac-Man graph and move to 'dist' folder
      - name: Generate Pac-Man Contribution Graph
        run: |
          mkdir -p dist
          curl -sLo dist/pacman-contribution-graph.svg "https://pacman-contribution-graph.abozanona.repl.co/svg?username=${{ github.repository_owner }}"

      # Step 3: Deploy to 'output' branch alongside Snake assets
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update Pac-Man contribution graph [skip ci]"
